export const companies = [
    {
        id: 1,
        name: "Sentry",
        role: "Software Engineer Intern (Summer 2025)",
        city: "San Francisco, CA",
        link: "https://boards.greenhouse.io/sentry/jobs/6145556?gh_src=b463ec651us&source=LinkedIn",
        imgUrl: "https://logo.clearbit.com/sentry.com",
        applyDate: "9/4/2024",
        status: "Rejected",
        updatedAt: "2024-09-09 19:34:01.903882",
        imageDomain: "sentry.com"
    },
    {
        id: 2,
        name: "Qorvous.inc",
        role: "Software Engineer Intern",
        city: "San Jose, CA",
        link: "https://career41.sapsf.com/portalcareer?_s.crb=I2pUnxf7SeSKqBVKtWXQyWU5HvCPGrKsnjoOIfVr6%252bU%253d",
        imgUrl: "https://logo.clearbit.com/Qorvo.com",
        applyDate: "9/4/2024",
        status: "Rejected",
        updatedAt: "2024-09-10 20:25:37.680914",
        imageDomain: "Qorvo.com"
    },
    {
        id: 3,
        name: "Roblox",
        role: "Software Engineer Intern (Summer 2025)",
        city: "San Mateo, CA (hybrid)",
        link: "https://careers.roblox.com/jobs/6086765",
        imgUrl: "https://logo.clearbit.com/roblox.com",
        applyDate: "9/4/2024",
        status: "Rejected",
        updatedAt: "2024-09-06 19:34:23.897726",
        imageDomain: "roblox.com"
    },
    {
        id: 4,
        name: "Verkada",
        role: "Software Engineering Intern, Backend (Winter/Summer 2025)",
        city: "San Mateo, CA",
        link: "https://job-boards.greenhouse.io/verkada/jobs/4482665007?gh_src=cda0ce657us",
        imgUrl: "https://logo.clearbit.com/verkada.com",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "verkada.com"
    },
    {
        id: 5,
        name: "Zip",
        role: "Software Engineer Intern (Summer 2025)",
        city: "San Francisco, CA",
        link: "https://job-boards.greenhouse.io/zip/jobs/5268304004",
        imgUrl: "https://logo.clearbit.com/ziphq.com",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "ziphq.com"
    },
    {
        id: 6,
        name: "Berkley Alternative Markets Tech",
        role: "Software Engineering Intern - Summer 2025",
        city: "Manassas, VA",
        link: "https://careers-berkley.icims.com/jobs/11097/software-engineering-intern---summer-2025/job?mode=submit_apply&ref=Simplify&src=Simplify&utm_source=Simplify",
        imgUrl: "https://logo.clearbit.com/berkleyalternativemarkets.tech",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "berkleyalternativemarkets.tech"
    },
    {
        id: 7,
        name: "ServiceNow",
        role: "UTG - Software Engineer Internships (Summer 2025)",
        city: "Santa Clara, CA",
        link: "https://careers.servicenow.com/en/jobs/744000011666405/utg-software-engineer-internships-summer-2025/?trid=2d92f286-613b-4daf-9dfa-6340ffbecf73",
        imgUrl: "https://logo.clearbit.com/servicenow.com",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "servicenow.com"
    },
    {
        id: 8,
        name: "DIRECTV",
        role: "2025 Information Technology Internship (STEM)",
        city: "Remote",
        link: "https://directv.wd1.myworkdayjobs.com/Careers/job/XMLNAME-2025-DIRECTV-Information-Technology-Internship--STEM-_R240282",
        imgUrl: "https://logo.clearbit.com/DIRECTV.com",
        applyDate: "9/4/2024",
        status: "Rejected",
        updatedAt: "2024-09-12 18:30:56.796152",
        imageDomain: "DIRECTV.com"
    },
    {
        id: 9,
        name: "IXL",
        role: "Software Engineer, Intern",
        city: "San Mateo, CA",
        link: "https://www.ixl.com/company/careers?gh_jid=7535493002",
        imgUrl: "https://logo.clearbit.com/ixl.com",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "ixl.com"
    },
    {
        id: 10,
        name: "Apple",
        role: "Software Engineering Internships",
        city: "San Jose",
        link: "https://jobs.apple.com/en-us/details/200554359/software-engineering-internships",
        imgUrl: "https://logo.clearbit.com/apple.com",
        applyDate: "9/4/2024",
        status: "Submitted",
        updatedAt: "2024-09-04 00:00:00.000000",
        imageDomain: "apple.com"
    }
];
